### PR TITLE
fix: hide dropdown when custom messages are empty

### LINKED ISSUE #219: Empty option messages shows an empty line in the dropdown.
When setting any of the option messages (createOptionMsg, duplicateOptionMsg, noMatchingOptionsMsg) to an empty string (`""`), the dropdowns show an empty line.

Here is it highlighted in red to improve visibility:

image

## Repro

Steps to reproduce the problem:

- Set any of createOptionMsg, duplicateOptionMsg, noMatchingOptionsMsg to `""`.
- Get in the matching state (create option, duplicate option, no matching options).

## Expected behavior

From a UI perspective, it is better not to display the dropdown at all in that case.

## Additional context

I implemented a fix and will open the MR.

### PR DESCRIPTION
**Pull request by nohehf**
Closes #219 

## Summary of major changes

- Aggregated the messages as `optionMessage` in a @const
- Don't show the `<li/>` element if the optionMessage is empty
- Renamed `add_option_msg_is_active` to `option_msg_is_active` for clarity

### Before
image

### After 
image

## Checklist

[ ] ~~has tests for any new functionality or bug fixes~~ -> Not applicable I believe
[ ] ~~has examples/docs for any new functionality~~ -> Not applicable

### CODE REVIEW

**Comment by janosh** [comment]
Thanks for the clear explanation and for going straight ahead with the fix. This is a good change! 👍

File: src/lib/MultiSelect.svelte [hunk 1]
```diff
@@ -124,12 +124,19 @@
...
     console.warn(
-      `MultiSelect's sortSelected and selectedOptionsDraggable should not be combined as any user re-orderings of selected options will be undone by sortSelected on component re-renders.`
+      `MultiSelect's sortSelected and selectedOptionsDraggable should not be combined as any ` +
+        `user re-orderings of selected options will be undone by sortSelected on component re-renders.`
+    )
+  }
+  if (allowUserOptions && !createOptionMsg) {
+    console.error(
+      `MultiSelect's allowUserOptions=${allowUserOptions} but createOptionMsg=${createOptionMsg} is falsy. ` +
+        `This prevents the "Add option" <span> from showing up, resulting in a confusing user experience.`
```
Comment (nohehf) [inline src/lib/MultiSelect.svelte:134]: I'm a bit surprised by this change. I don't think it should error for this. It is used in the docs and is my use case. A user expects no message if it is set to an empty string.

**Review by nohehf — COMMENTED** [review]
Thank you for merging @janosh! I left a review on the console.error, lmk what you think.

File: src/lib/MultiSelect.svelte (hunk 1 above)
Comment (janosh) [reply src/lib/MultiSelect.svelte:134]: Ah, right. Hadn't thought about the tag component use case where you don't necessarily have a pre-defined set of tags.

Maybe we could treat `createOptionMsg={null}` as a special case to signal you really don't want to show a `createOptionMsg` so it shouldn't through an error. I still think it would be good to alert devevlopers if they pass `createOptionMsg=""` or `createOptionMsg={undefined}` since it might happen by accident.

Comment (nohehf) [reply src/lib/MultiSelect.svelte:134]: Yes, this sounds like a nice solution! I can open a new MR if you want :)

Comment (janosh) [reply src/lib/MultiSelect.svelte:134]: That'd be great!
